excluded: # paths to ignore during linting. Takes precedence over `included`.
  - DerivedData
  - ResearchKit
disabled_rules:
  - multiple_closures_with_trailing_closure
  - weak_delegate
  - file_length
  - function_body_length
